### ISSUE TITLE
Issue with `plot()` when textlabel to a path contains `curve: 0`

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/svgdigitizer#176]
Under certain circumstances, which could not reproduce `cv.plot` and `svgplot.plot` fail, when the textlabel of a path contains `curve: 0`.

I could not elucidate the origin of that problem.
```sh
146         >>> cv.plot()
UNEXPECTED EXCEPTION: TclError('Can\'t find a usable init.tcl in the following directories: \n    C:/Miniconda3/envs/svgdigitizer-build/Library/lib/tcl8.6 C:/Miniconda3/envs/lib/tcl8.6 C:/Miniconda3/lib/tcl8.6 C:/Miniconda3/envs/library C:/Miniconda3/library C:/Miniconda3/tcl8.6.12/library C:/tcl8.6.12/library\n\nC:/Miniconda3/envs/svgdigitizer-build/Library/lib/tcl8.6/init.tcl: couldn\'t read file "C:/Miniconda3/envs/svgdigitizer-build/Library/lib/tcl8.6/init.tcl": No error\ncouldn\'t read file "C:/Miniconda3/envs/svgdigitizer-build/Library/lib/tcl8.6/init.tcl": No error\n    while executing\n"source C:/Miniconda3/envs/svgdigitizer-build/Library/lib/tcl8.6/init.tcl"\n    ("uplevel" body line 1)\n    invoked from within\n"uplevel #0 [list source $tclfile]"\n\n\nThis probably means that Tcl wasn\'t installed properly.\n')
Traceback (most recent call last):
  File "C:\Miniconda3\envs\svgdigitizer-build\lib\doctest.py", line 1350, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest svgdigitizer.electrochemistry.cv.CV[7]>", line 1, in <module>
  File "X:\github\svgdigitizer\svgdigitizer\electrochemistry\cv.py", line 870, in plot
    self.df.plot(
  File "C:\Miniconda3\envs\svgdigitizer-build\lib\site-packages\pandas\plotting\_core.py", line 1000, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "C:\Miniconda3\envs\svgdigitizer-build\lib\site-packages\pandas\plotting\_matplotlib\__init__.py", line 71, in plot
    plot_obj.generate()
  File "C:\Miniconda3\envs\svgdigitizer-build\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 451, in generate
    self._setup_subplots()
  File "C:\Miniconda3\envs\svgdigitizer-build\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 512, in _setup_subplots
    fig = self.plt.figure(figsize=self.figsize)
  File "C:\Miniconda3\envs\svgdigitizer-build\lib\site-packages\matplotlib\_api\deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "C:\Miniconda3\envs\svgdigitizer-build\lib\site-packages\matplotlib\pyplot.py", line 783, in figure
    manager = new_figure_manager(
  File "C:\Miniconda3\envs\svgdigitizer-build\lib\site-packages\matplotlib\pyplot.py", line 359, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
  File "C:\Miniconda3\envs\svgdigitizer-build\lib\site-packages\matplotlib\backend_bases.py", line 3513, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "C:\Miniconda3\envs\svgdigitizer-build\lib\site-packages\matplotlib\backend_bases.py", line 3518, in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
  File "C:\Miniconda3\envs\svgdigitizer-build\lib\site-packages\matplotlib\backend_bases.py", line 1703, in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
  File "C:\Miniconda3\envs\svgdigitizer-build\lib\site-packages\matplotlib\backends\_backend_tk.py", line 457, in create_with_canvas
    window = tk.Tk(className="matplotlib")
  File "C:\Miniconda3\envs\svgdigitizer-build\lib\tkinter\__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    C:/Miniconda3/envs/svgdigitizer-build/Library/lib/tcl8.6 C:/Miniconda3/envs/lib/tcl8.6 C:/Miniconda3/lib/tcl8.6 C:/Miniconda3/envs/library C:/Miniconda3/library C:/Miniconda3/tcl8.6.12/library C:/tcl8.6.12/library

C:/Miniconda3/envs/svgdigitizer-build/Library/lib/tcl8.6/init.tcl: couldn't read file "C:/Miniconda3/envs/svgdigitizer-build/Library/lib/tcl8.6/init.tcl": No error
couldn't read file "C:/Miniconda3/envs/svgdigitizer-build/Library/lib/tcl8.6/init.tcl": No error
    while executing
"source C:/Miniconda3/envs/svgdigitizer-build/Library/lib/tcl8.6/init.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $tclfile]"


This probably means that Tcl wasn't installed properly.
```

**Comment by saraedum** [comment]
Seems your system would like to use Tcl/Tk to display a plot. There's probably a matplotlib setting that you can use to forbid that.

I don't understand why it does not just open a browser instead? Are you in some weird visual studio code environment here?

**Comment by DunklesArchipel** [comment]
I work in VS Code but I am not aware of some specific environment. It is also odd that it happens rather in a rather inconsistent way.

I'll keep an eye on it.

**Comment by DunklesArchipel** [comment]
It does not seem to be related to the curve label. The issue appears sporadically. Running pytest several times usually resolves the issue in VSCode.
