### ISSUE TITLE
Rever release issue

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/svgdigitizer#207]
@saraedum @linuxrider 
There seems to be an issue with `rever`, which does not find a `setup.py` and thus can not make a new release.
```sh
From https://github.com/echemdb/svgdigitizer
 * branch            HEAD       -> FETCH_HEAD
←[96mactivity-start←[35m:←[31mversion_bump←[35m:←[97mstarting activity version_bump←[0m
[master 1f6a552] bumped version to 0.12.0
 2 files changed, 2 insertions(+), 2 deletions(-)
←[96mactivity-end←[35m:←[31mversion_bump←[35m:←[97mactivity version_bump complete←[0m
←[96mactivity-start←[35m:←[31mchangelog←[35m:←[97mstarting activity changelog←[0m
[master 9aec92b] Updated CHANGELOG for 0.12.0
 5 files changed, 21 insertions(+), 12 deletions(-)
 delete mode 100644 doc/news/dependencies2.rst
 delete mode 100644 doc/news/macos.rst
 delete mode 100644 doc/news/pyproject.rst
 delete mode 100644 doc/news/python3.12.rst
←[96mactivity-end←[35m:←[31mchangelog←[35m:←[97mactivity changelog complete←[0m
←[96mactivity-start←[35m:←[31mtag←[35m:←[97mstarting activity tag←[0m
←[96mactivity-end←[35m:←[31mtag←[35m:←[97mactivity tag complete←[0m
←[96mactivity-start←[35m:←[31mpush_tag←[35m:←[97mstarting activity push_tag←[0m
Enumerating objects: 16, done.
Counting objects: 100% (16/16), done.
Delta compression using up to 8 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (10/10), 1.04 KiB | 535.00 KiB/s, done.
Total 10 (delta 7), reused 1 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (7/7), completed with 5 local objects.
remote: Bypassed rule violations for refs/heads/master:
remote:
remote: - Changes must be made through a pull request.
remote:
remote: - 20 of 20 required status checks are expected.
remote:
To github.com:echemdb/svgdigitizer.git
   409b9c5..9aec92b  master -> master
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:echemdb/svgdigitizer.git
 * [new tag]         0.12.0 -> 0.12.0
←[96mactivity-end←[35m:←[31mpush_tag←[35m:←[97mactivity push_tag complete←[0m
←[96mactivity-start←[35m:←[31mpypi←[35m:←[97mstarting activity pypi←[0m
C:\MINICONDA3\ENVS\SVGDIGITIZER-BUILD\PYTHON.EXE: can't open file 'F:\\Github\\svgdigitizer\\setup.py': [Errno 2] No such file or directory
activity-error:pypi:activity failed with exception:
Traceback (most recent call last):
  File "C:\Miniconda3\envs\svgdigitizer-build\Lib\site-packages\rever\activity.xsh", line 83, in __call__
    self.func(*args, **kwargs)

  File "C:\Miniconda3\envs\svgdigitizer-build\Lib\site-packages\rever\activities\pypi.xsh", line 161, in _func
    p = ![$PYTHON setup.py @(build_commands)]

  File "C:\Miniconda3\envs\svgdigitizer-build\Lib\site-packages\xonsh\built_ins.py", line 205, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\svgdigitizer-build\Lib\site-packages\xonsh\procs\specs.py", line 907, in run_subproc
    return _run_specs(specs, cmds)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\svgdigitizer-build\Lib\site-packages\xonsh\procs\specs.py", line 942, in _run_specs
    command.end()
  File "C:\Miniconda3\envs\svgdigitizer-build\Lib\site-packages\xonsh\procs\pipelines.py", line 458, in end
    self._end(tee_output=tee_output)
  File "C:\Miniconda3\envs\svgdigitizer-build\Lib\site-packages\xonsh\procs\pipelines.py", line 477, in _end
    self._raise_subproc_error()
  File "C:\Miniconda3\envs\svgdigitizer-build\Lib\site-packages\xonsh\procs\pipelines.py", line 602, in _raise_subproc_error
    raise subprocess.CalledProcessError(rtn, spec.args, output=self.output)
subprocess.CalledProcessError: Command '['C:\\Miniconda3\\envs\\svgdigitizer-build\\python.exe', 'setup.py', 'sdist', '--dist-dir', 'rever\\dist', 'bdist_wheel', '--dist-dir', 'rever\\dist']' returned non-zero exit status 2.
rewinding to 9aec92bedc40aabbb697d62cfe815f5b8ce959d5
```

**Comment by saraedum** [comment]
Yes, this needs to be fixed in rever itself.

A workaround is, e.g., here: https://github.com/flatsurf/cppyythonizations/commit/d40ced6abda1bd35409f9235d67eb7d6b1ea6faa
