### ISSUE TITLE
Bug: `ModuleNotFoundError: No module named 'pyparsing'`

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/svgdigitizer#214]
Experienced an issue when installing `svgdigitizer` in a new environment with pip in Win11.

```sh
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\svgdigitizer-script.py", line 33, in <module>
    sys.exit(load_entry_point('svgdigitizer', 'console_scripts', 'svgdigitizer')())
  File "C:\Miniconda\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Miniconda\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Miniconda\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Miniconda\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Miniconda\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "e:\github\echemdb\svgdigitizer\svgdigitizer\entrypoint.py", line 361, in digitize_cv
    from svgdigitizer.electrochemistry.cv import CV
  File "e:\github\echemdb\svgdigitizer\svgdigitizer\electrochemistry\cv.py", line 51, in <module>
    import matplotlib.pyplot as plt
  File "C:\Miniconda\lib\site-packages\matplotlib\__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Miniconda\lib\site-packages\matplotlib\rcsetup.py", line 29, in <module>
    from matplotlib._fontconfig_pattern import parse_fontconfig_pattern
  File "C:\Miniconda\lib\site-packages\matplotlib\_fontconfig_pattern.py", line 15, in <module>
    from pyparsing import (
ModuleNotFoundError: No module named 'pyparsing'
```

when pip installing `pyparsing`
```
$ pip install pyparsing
Requirement already satisfied: pyparsing in c:\miniconda\lib\site-packages (3.0.6)
```

solved with:
```sh
$ mamba install -c conda-forge pyparsing
```

**Comment by saraedum** [comment]
I don't understand why the `pip` one wasn't good enough. Can you reproduce this?

**Comment by DunklesArchipel** [comment]
Could not be reproduced and is possibly outdated.
